services:
  - name: restaurant-dashboard
    region: oregon
    runtime: node
    repo: https://github.com/Bobbywealth/restaurant-dashboard
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOAST_CLIENT_ID
        value: fWtDwDjMLuvklqFykpMuY9tbz19g1th9
      - key: TOAST_CLIENT_SECRET
        value: 3_uTSyXKvPZwZUMYlCV-PJFd8Twka8QnlORetJI2kxLe1ki7aW5c9ot3ySMBykwp
      - key: RESTAURANT_GUID
        value: 8d0d8d7b-1fcc-43fd-8be5-1413efbaaef7
      - key: DATABASE_URL
        value: ""
        sync: false
      - key: RESTAURANT_NAME
        value: "Top Taste Jamaican Restaurant"
